# .streamlit/secrets.toml

GROK_API_KEY = "xai-5lMLN1cjRbJpl6AFu5198KT3MG9LxPdiLd0cVKWfE1QiO6ZHPcCeCfUgcDXdSluZ9s1DPyBRgZuAhh1R"

# Nếu bạn có Telegram
TELEGRAM_TOKEN = "8516741675:AAE8rdixZX6x7e-ZtXXH1YjZC-PehUFkLOA"
TELEGRAM_CHAT_ID = "1247850754"
