# .streamlit/secrets.toml

GROK_API_KEY = "xai-eXIvX5fzUR6jdBQe8hxd6j88m8a1wsGZI5KVQNnhXkxiXuNZXljk8UCG03v0a6Q6o0VPwgM3RDQZCTyh"

# Nếu bạn có Telegram
TELEGRAM_TOKEN = "8516741675:AAE8rdixZX6x7e-ZtXXH1YjZC-PehUFkLOA"
TELEGRAM_CHAT_ID = "1247850754"
